//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4959
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=2.0.50727.3038。
// 
namespace tdps._20201._007 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    [System.Xml.Serialization.XmlRootAttribute("taxML", Namespace="", IsNullable=false)]
    public partial class T_taxML {
        
        private T_taxMLSbbJzyyys sbbJzyyysField;
        
        private T_taxMLVersion versionField;
        
        private T_taxMLName nameField;
        
        private T_taxMLCnName cnNameField;
        
        /// <remarks/>
        public T_taxMLSbbJzyyys sbbJzyyys {
            get {
                return this.sbbJzyyysField;
            }
            set {
                this.sbbJzyyysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLCnName cnName {
            get {
                return this.cnNameField;
            }
            set {
                this.cnNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyys {
        
        private T_taxMLSbbJzyyysHead headField;
        
        private T_taxMLSbbJzyyysBody bodyField;
        
        /// <remarks/>
        public T_taxMLSbbJzyyysHead head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbJzyyysBody body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysHead {
        
        private sbbPublicHead publicHeadField;
        
        /// <remarks/>
        public sbbPublicHead publicHead {
            get {
                return this.publicHeadField;
            }
            set {
                this.publicHeadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class sbbPublicHead {
        
        private string nsrsbhField;
        
        private string nsrmcField;
        
        private string tbrqField;
        
        private string tbrField;
        
        private rqfw sssqField;
        
        private string dymmField;
        
        /// <remarks/>
        public string nsrsbh {
            get {
                return this.nsrsbhField;
            }
            set {
                this.nsrsbhField = value;
            }
        }
        
        /// <remarks/>
        public string nsrmc {
            get {
                return this.nsrmcField;
            }
            set {
                this.nsrmcField = value;
            }
        }
        
        /// <remarks/>
        public string tbrq {
            get {
                return this.tbrqField;
            }
            set {
                this.tbrqField = value;
            }
        }
        
        /// <remarks/>
        public string tbr {
            get {
                return this.tbrField;
            }
            set {
                this.tbrField = value;
            }
        }
        
        /// <remarks/>
        public rqfw sssq {
            get {
                return this.sssqField;
            }
            set {
                this.sssqField = value;
            }
        }
        
        /// <remarks/>
        public string dymm {
            get {
                return this.dymmField;
            }
            set {
                this.dymmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class rqfw {
        
        private string rqQField;
        
        private string rqZField;
        
        /// <remarks/>
        public string rqQ {
            get {
                return this.rqQField;
            }
            set {
                this.rqQField = value;
            }
        }
        
        /// <remarks/>
        public string rqZ {
            get {
                return this.rqZField;
            }
            set {
                this.rqZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class T8_ysxm {
        
        private long lcField;
        
        private string ysxmdmField;
        
        private string ysxmmcField;
        
        private double jssrField;
        
        private double jcjexjField;
        
        private double zfgckField;
        
        private double jcsbkField;
        
        private double qtjcjeField;
        
        private double yyeField;
        
        private double mssrField;
        
        private double slField;
        
        private double skxjField;
        
        private double ynseField;
        
        private double mseField;
        
        private double qjseField;
        
        private double djseField;
        
        private double ynsexjField;
        
        private double yjynseField;
        
        private double ybkjseField;
        
        private double yjqjseField;
        
        private double yjsexjField;
        
        private double qmyjseField;
        
        private double qmyjqjseField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public string ysxmdm {
            get {
                return this.ysxmdmField;
            }
            set {
                this.ysxmdmField = value;
            }
        }
        
        /// <remarks/>
        public string ysxmmc {
            get {
                return this.ysxmmcField;
            }
            set {
                this.ysxmmcField = value;
            }
        }
        
        /// <remarks/>
        public double jssr {
            get {
                return this.jssrField;
            }
            set {
                this.jssrField = value;
            }
        }
        
        /// <remarks/>
        public double jcjexj {
            get {
                return this.jcjexjField;
            }
            set {
                this.jcjexjField = value;
            }
        }
        
        /// <remarks/>
        public double zfgck {
            get {
                return this.zfgckField;
            }
            set {
                this.zfgckField = value;
            }
        }
        
        /// <remarks/>
        public double jcsbk {
            get {
                return this.jcsbkField;
            }
            set {
                this.jcsbkField = value;
            }
        }
        
        /// <remarks/>
        public double qtjcje {
            get {
                return this.qtjcjeField;
            }
            set {
                this.qtjcjeField = value;
            }
        }
        
        /// <remarks/>
        public double yye {
            get {
                return this.yyeField;
            }
            set {
                this.yyeField = value;
            }
        }
        
        /// <remarks/>
        public double mssr {
            get {
                return this.mssrField;
            }
            set {
                this.mssrField = value;
            }
        }
        
        /// <remarks/>
        public double sl {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        public double skxj {
            get {
                return this.skxjField;
            }
            set {
                this.skxjField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public double mse {
            get {
                return this.mseField;
            }
            set {
                this.mseField = value;
            }
        }
        
        /// <remarks/>
        public double qjse {
            get {
                return this.qjseField;
            }
            set {
                this.qjseField = value;
            }
        }
        
        /// <remarks/>
        public double djse {
            get {
                return this.djseField;
            }
            set {
                this.djseField = value;
            }
        }
        
        /// <remarks/>
        public double ynsexj {
            get {
                return this.ynsexjField;
            }
            set {
                this.ynsexjField = value;
            }
        }
        
        /// <remarks/>
        public double yjynse {
            get {
                return this.yjynseField;
            }
            set {
                this.yjynseField = value;
            }
        }
        
        /// <remarks/>
        public double ybkjse {
            get {
                return this.ybkjseField;
            }
            set {
                this.ybkjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjqjse {
            get {
                return this.yjqjseField;
            }
            set {
                this.yjqjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjsexj {
            get {
                return this.yjsexjField;
            }
            set {
                this.yjsexjField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjse {
            get {
                return this.qmyjseField;
            }
            set {
                this.qmyjseField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjqjse {
            get {
                return this.qmyjqjseField;
            }
            set {
                this.qmyjqjseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysBody {
        
        private T_taxMLSbbJzyyysBodySbxm[] sbxmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sbxm", IsNullable=false)]
        public T_taxMLSbbJzyyysBodySbxm[] sbxms {
            get {
                return this.sbxmsField;
            }
            set {
                this.sbxmsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysBodySbxm {
        
        private string sbxmdmField;
        
        private string sbxmmcField;
        
        private T_taxMLSbbJzyyysBodySbxmYsxms ysxmsField;
        
        private T_taxMLSbbJzyyysBodySbxmHjxx hjxxField;
        
        /// <remarks/>
        public string sbxmdm {
            get {
                return this.sbxmdmField;
            }
            set {
                this.sbxmdmField = value;
            }
        }
        
        /// <remarks/>
        public string sbxmmc {
            get {
                return this.sbxmmcField;
            }
            set {
                this.sbxmmcField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbJzyyysBodySbxmYsxms ysxms {
            get {
                return this.ysxmsField;
            }
            set {
                this.ysxmsField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbJzyyysBodySbxmHjxx hjxx {
            get {
                return this.hjxxField;
            }
            set {
                this.hjxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysBodySbxmYsxms {
        
        private T8_ysxm[] ysxmField;
        private T_taxMLSbbJzyyysBodySbxmYsxmsXjxx xjxxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ysxm")]
        public T8_ysxm[] ysxm {
            get {
                return this.ysxmField;
            }
            set {
                this.ysxmField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbJzyyysBodySbxmYsxmsXjxx xjxx {
            get {
                return this.xjxxField;
            }
            set {
                this.xjxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysBodySbxmYsxmsXjxx {
        
        private long lcField;
        
        private string ysxmdmField;
        
        private string ysxmmcField;
        
        private double jssrField;
        
        private double jcjexjField;
        
        private double zfgckField;
        
        private double jcsbkField;
        
        private double qtjcjeField;
        
        private double yyeField;
        
        private double mssrField;
        
        private double slField;
        
        private double skxjField;
        
        private double ynseField;
        
        private double mseField;
        
        private double qjseField;
        
        private double djseField;
        
        private double ynsexjField;
        
        private double yjynseField;
        
        private double ybkjseField;
        
        private double yjqjseField;
        
        private double yjsexjField;
        
        private double qmyjseField;
        
        private double qmyjqjseField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public string ysxmdm {
            get {
                return this.ysxmdmField;
            }
            set {
                this.ysxmdmField = value;
            }
        }
        
        /// <remarks/>
        public string ysxmmc {
            get {
                return this.ysxmmcField;
            }
            set {
                this.ysxmmcField = value;
            }
        }
        
        /// <remarks/>
        public double jssr {
            get {
                return this.jssrField;
            }
            set {
                this.jssrField = value;
            }
        }
        
        /// <remarks/>
        public double jcjexj {
            get {
                return this.jcjexjField;
            }
            set {
                this.jcjexjField = value;
            }
        }
        
        /// <remarks/>
        public double zfgck {
            get {
                return this.zfgckField;
            }
            set {
                this.zfgckField = value;
            }
        }
        
        /// <remarks/>
        public double jcsbk {
            get {
                return this.jcsbkField;
            }
            set {
                this.jcsbkField = value;
            }
        }
        
        /// <remarks/>
        public double qtjcje {
            get {
                return this.qtjcjeField;
            }
            set {
                this.qtjcjeField = value;
            }
        }
        
        /// <remarks/>
        public double yye {
            get {
                return this.yyeField;
            }
            set {
                this.yyeField = value;
            }
        }
        
        /// <remarks/>
        public double mssr {
            get {
                return this.mssrField;
            }
            set {
                this.mssrField = value;
            }
        }
        
        /// <remarks/>
        public double sl {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        public double skxj {
            get {
                return this.skxjField;
            }
            set {
                this.skxjField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public double mse {
            get {
                return this.mseField;
            }
            set {
                this.mseField = value;
            }
        }
        
        /// <remarks/>
        public double qjse {
            get {
                return this.qjseField;
            }
            set {
                this.qjseField = value;
            }
        }
        
        /// <remarks/>
        public double djse {
            get {
                return this.djseField;
            }
            set {
                this.djseField = value;
            }
        }
        
        /// <remarks/>
        public double ynsexj {
            get {
                return this.ynsexjField;
            }
            set {
                this.ynsexjField = value;
            }
        }
        
        /// <remarks/>
        public double yjynse {
            get {
                return this.yjynseField;
            }
            set {
                this.yjynseField = value;
            }
        }
        
        /// <remarks/>
        public double ybkjse {
            get {
                return this.ybkjseField;
            }
            set {
                this.ybkjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjqjse {
            get {
                return this.yjqjseField;
            }
            set {
                this.yjqjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjsexj {
            get {
                return this.yjsexjField;
            }
            set {
                this.yjsexjField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjse {
            get {
                return this.qmyjseField;
            }
            set {
                this.qmyjseField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjqjse {
            get {
                return this.qmyjqjseField;
            }
            set {
                this.qmyjqjseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbJzyyysBodySbxmHjxx {
        
        private long lcField;
        
        private double jssrField;
        
        private double jcjexjField;
        
        private double zfgckField;
        
        private double jcsbkField;
        
        private double qtjcjeField;
        
        private double yyeField;
        
        private double mssrField;
        
        private double slField;
        
        private double skxjField;
        
        private double ynseField;
        
        private double mseField;
        
        private double qjseField;
        
        private double djseField;
        
        private double ynsexjField;
        
        private double yjynseField;
        
        private double ybkjseField;
        
        private double yjqjseField;
        
        private double yjsexjField;
        
        private double qmyjseField;
        
        private double qmyjqjseField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public double jssr {
            get {
                return this.jssrField;
            }
            set {
                this.jssrField = value;
            }
        }
        
        /// <remarks/>
        public double jcjexj {
            get {
                return this.jcjexjField;
            }
            set {
                this.jcjexjField = value;
            }
        }
        
        /// <remarks/>
        public double zfgck {
            get {
                return this.zfgckField;
            }
            set {
                this.zfgckField = value;
            }
        }
        
        /// <remarks/>
        public double jcsbk {
            get {
                return this.jcsbkField;
            }
            set {
                this.jcsbkField = value;
            }
        }
        
        /// <remarks/>
        public double qtjcje {
            get {
                return this.qtjcjeField;
            }
            set {
                this.qtjcjeField = value;
            }
        }
        
        /// <remarks/>
        public double yye {
            get {
                return this.yyeField;
            }
            set {
                this.yyeField = value;
            }
        }
        
        /// <remarks/>
        public double mssr {
            get {
                return this.mssrField;
            }
            set {
                this.mssrField = value;
            }
        }
        
        /// <remarks/>
        public double sl {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        public double skxj {
            get {
                return this.skxjField;
            }
            set {
                this.skxjField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public double mse {
            get {
                return this.mseField;
            }
            set {
                this.mseField = value;
            }
        }
        
        /// <remarks/>
        public double qjse {
            get {
                return this.qjseField;
            }
            set {
                this.qjseField = value;
            }
        }
        
        /// <remarks/>
        public double djse {
            get {
                return this.djseField;
            }
            set {
                this.djseField = value;
            }
        }
        
        /// <remarks/>
        public double ynsexj {
            get {
                return this.ynsexjField;
            }
            set {
                this.ynsexjField = value;
            }
        }
        
        /// <remarks/>
        public double yjynse {
            get {
                return this.yjynseField;
            }
            set {
                this.yjynseField = value;
            }
        }
        
        /// <remarks/>
        public double ybkjse {
            get {
                return this.ybkjseField;
            }
            set {
                this.ybkjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjqjse {
            get {
                return this.yjqjseField;
            }
            set {
                this.yjqjseField = value;
            }
        }
        
        /// <remarks/>
        public double yjsexj {
            get {
                return this.yjsexjField;
            }
            set {
                this.yjsexjField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjse {
            get {
                return this.qmyjseField;
            }
            set {
                this.qmyjseField = value;
            }
        }
        
        /// <remarks/>
        public double qmyjqjse {
            get {
                return this.qmyjqjseField;
            }
            set {
                this.qmyjqjseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("V1.0")]
        V10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLName {
        
        /// <remarks/>
        sbbJzyyys,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLCnName {
        
        /// <remarks/>
        建筑业营业税,
    }
}
