//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4959
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=2.0.50727.3038。
// 
namespace tdps._20201._006 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    [System.Xml.Serialization.XmlRootAttribute("taxML", Namespace="", IsNullable=false)]
    public partial class T_taxML {
        
        private T_taxMLSbbYdtgjzylwskjnqksbb sbbYdtgjzylwskjnqksbbField;
        
        private T_taxMLVersion versionField;
        
        private T_taxMLName nameField;
        
        private T_taxMLCnName cnNameField;
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbb sbbYdtgjzylwskjnqksbb {
            get {
                return this.sbbYdtgjzylwskjnqksbbField;
            }
            set {
                this.sbbYdtgjzylwskjnqksbbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public T_taxMLCnName cnName {
            get {
                return this.cnNameField;
            }
            set {
                this.cnNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbb {
        
        private T_taxMLSbbYdtgjzylwskjnqksbbHead headField;
        
        private T_taxMLSbbYdtgjzylwskjnqksbbBody bodyField;
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbbHead head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbbBody body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbbHead {
        
        private sbbPublicHead publicHeadField;
        
        /// <remarks/>
        public sbbPublicHead publicHead {
            get {
                return this.publicHeadField;
            }
            set {
                this.publicHeadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class sbbPublicHead {
        
        private string nsrsbhField;
        
        private string nsrmcField;
        
        private string tbrqField;
        
        private string tbrField;
        
        private rqfw sssqField;
        
        private string dymmField;
        
        /// <remarks/>
        public string nsrsbh {
            get {
                return this.nsrsbhField;
            }
            set {
                this.nsrsbhField = value;
            }
        }
        
        /// <remarks/>
        public string nsrmc {
            get {
                return this.nsrmcField;
            }
            set {
                this.nsrmcField = value;
            }
        }
        
        /// <remarks/>
        public string tbrq {
            get {
                return this.tbrqField;
            }
            set {
                this.tbrqField = value;
            }
        }
        
        /// <remarks/>
        public string tbr {
            get {
                return this.tbrField;
            }
            set {
                this.tbrField = value;
            }
        }
        
        /// <remarks/>
        public rqfw sssq {
            get {
                return this.sssqField;
            }
            set {
                this.sssqField = value;
            }
        }
        
        /// <remarks/>
        public string dymm {
            get {
                return this.dymmField;
            }
            set {
                this.dymmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class rqfw {
        
        private string rqQField;
        
        private string rqZField;
        
        /// <remarks/>
        public string rqQ {
            get {
                return this.rqQField;
            }
            set {
                this.rqQField = value;
            }
        }
        
        /// <remarks/>
        public string rqZ {
            get {
                return this.rqZField;
            }
            set {
                this.rqZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    
    public partial class T6_ysxm {
        
        private string ysxmdmField;
        
        private string ysxmmcField;
        
        private T6_ysxmYsxmmxs ysxmmxsField;
        
        /// <remarks/>
        public string ysxmdm {
            get {
                return this.ysxmdmField;
            }
            set {
                this.ysxmdmField = value;
            }
        }
        
        /// <remarks/>
        public string ysxmmc {
            get {
                return this.ysxmmcField;
            }
            set {
                this.ysxmmcField = value;
            }
        }
        
        /// <remarks/>
        public T6_ysxmYsxmmxs ysxmmxs {
            get {
                return this.ysxmmxsField;
            }
            set {
                this.ysxmmxsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T6_ysxmYsxmmxs {
        
        private T6_ysxmYsxmmxsYsxmmx[] ysxmmxField;
        
        /// <remarks/>
        public T6_ysxmYsxmmxsYsxmmx[] ysxmmx {
            get {
                return this.ysxmmxField;
            }
            set {
                this.ysxmmxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T6_ysxmYsxmmxsYsxmmx {
        
        private long lcField;
        
        private double ynseField;
        
        private string ynjkpzhField;
        
        private double yjseField;
        
        private string yjjkpzhField;
        
        private string kjsssjqField;
        
        private string kjsssjzField;
        
        private string kjnsrsbhField;
        
        private double yrkyysseField;
        
        private string yrkjkpzhField;
        
        private string jksssjqField;
        
        private string jksssjzField;
        
        private double hzjmseField;
        
        private string jmpzwshField;
        
        private string pzwsqsyField;
        
        private string pzwszzyField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public string ynjkpzh {
            get {
                return this.ynjkpzhField;
            }
            set {
                this.ynjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public double yjse {
            get {
                return this.yjseField;
            }
            set {
                this.yjseField = value;
            }
        }
        
        /// <remarks/>
        public string yjjkpzh {
            get {
                return this.yjjkpzhField;
            }
            set {
                this.yjjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjq {
            get {
                return this.kjsssjqField;
            }
            set {
                this.kjsssjqField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjz {
            get {
                return this.kjsssjzField;
            }
            set {
                this.kjsssjzField = value;
            }
        }
        
        /// <remarks/>
        public string kjnsrsbh {
            get {
                return this.kjnsrsbhField;
            }
            set {
                this.kjnsrsbhField = value;
            }
        }
        
        /// <remarks/>
        public double yrkyysse {
            get {
                return this.yrkyysseField;
            }
            set {
                this.yrkyysseField = value;
            }
        }
        
        /// <remarks/>
        public string yrkjkpzh {
            get {
                return this.yrkjkpzhField;
            }
            set {
                this.yrkjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjq {
            get {
                return this.jksssjqField;
            }
            set {
                this.jksssjqField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjz {
            get {
                return this.jksssjzField;
            }
            set {
                this.jksssjzField = value;
            }
        }
        
        /// <remarks/>
        public double hzjmse {
            get {
                return this.hzjmseField;
            }
            set {
                this.hzjmseField = value;
            }
        }
        
        /// <remarks/>
        public string jmpzwsh {
            get {
                return this.jmpzwshField;
            }
            set {
                this.jmpzwshField = value;
            }
        }
        
        /// <remarks/>
        public string pzwsqsy {
            get {
                return this.pzwsqsyField;
            }
            set {
                this.pzwsqsyField = value;
            }
        }
        
        /// <remarks/>
        public string pzwszzy {
            get {
                return this.pzwszzyField;
            }
            set {
                this.pzwszzyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbbBody {
        
        private T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxms ysxmsField;

        private T_taxMLSbbYdtgjzylwskjnqksbbBodyHjxx hjxxField;
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxms ysxms {
            get {
                return this.ysxmsField;
            }
            set {
                this.ysxmsField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbbBodyHjxx hjxx {
            get {
                return this.hjxxField;
            }
            set {
                this.hjxxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxms {
        
        private T6_ysxm[] ysxmField;
        
        private T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxmsXjxx xjxxField;

        private T6_ysxm dkdjxmField;
        
        /// <remarks/>
        public T6_ysxm[] ysxm {
            get {
                return this.ysxmField;
            }
            set {
                this.ysxmField = value;
            }
        }
        
        /// <remarks/>
        public T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxmsXjxx xjxx {
            get {
                return this.xjxxField;
            }
            set {
                this.xjxxField = value;
            }
        }

        public T6_ysxm dkdjxm {
            get
            {
                return this.dkdjxmField;
            }
            set
            {
                this.dkdjxmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbbBodyYsxmsXjxx {
        
        private long lcField;
        
        private double ynseField;
        
        private string ynjkpzhField;
        
        private double yjseField;
        
        private string yjjkpzhField;
        
        private string kjsssjqField;
        
        private string kjsssjzField;
        
        private string kjnsrsbhField;
        
        private double yrkyysseField;
        
        private string yrkjkpzhField;
        
        private string jksssjqField;
        
        private string jksssjzField;
        
        private double hzjmseField;
        
        private string jmpzwshField;
        
        private string pzwsqsyField;
        
        private string pzwszzyField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public string ynjkpzh {
            get {
                return this.ynjkpzhField;
            }
            set {
                this.ynjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public double yjse {
            get {
                return this.yjseField;
            }
            set {
                this.yjseField = value;
            }
        }
        
        /// <remarks/>
        public string yjjkpzh {
            get {
                return this.yjjkpzhField;
            }
            set {
                this.yjjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjq {
            get {
                return this.kjsssjqField;
            }
            set {
                this.kjsssjqField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjz {
            get {
                return this.kjsssjzField;
            }
            set {
                this.kjsssjzField = value;
            }
        }
        
        /// <remarks/>
        public string kjnsrsbh {
            get {
                return this.kjnsrsbhField;
            }
            set {
                this.kjnsrsbhField = value;
            }
        }
        
        /// <remarks/>
        public double yrkyysse {
            get {
                return this.yrkyysseField;
            }
            set {
                this.yrkyysseField = value;
            }
        }
        
        /// <remarks/>
        public string yrkjkpzh {
            get {
                return this.yrkjkpzhField;
            }
            set {
                this.yrkjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjq {
            get {
                return this.jksssjqField;
            }
            set {
                this.jksssjqField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjz {
            get {
                return this.jksssjzField;
            }
            set {
                this.jksssjzField = value;
            }
        }
        
        /// <remarks/>
        public double hzjmse {
            get {
                return this.hzjmseField;
            }
            set {
                this.hzjmseField = value;
            }
        }
        
        /// <remarks/>
        public string jmpzwsh {
            get {
                return this.jmpzwshField;
            }
            set {
                this.jmpzwshField = value;
            }
        }
        
        /// <remarks/>
        public string pzwsqsy {
            get {
                return this.pzwsqsyField;
            }
            set {
                this.pzwsqsyField = value;
            }
        }
        
        /// <remarks/>
        public string pzwszzy {
            get {
                return this.pzwszzyField;
            }
            set {
                this.pzwszzyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class T_taxMLSbbYdtgjzylwskjnqksbbBodyHjxx {
        
        private long lcField;
        
        private double ynseField;
        
        private string ynjkpzhField;
        
        private double yjseField;
        
        private string yjjkpzhField;
        
        private string kjsssjqField;
        
        private string kjsssjzField;
        
        private string kjnsrsbhField;
        
        private double yrkyysseField;
        
        private string yrkjkpzhField;
        
        private string jksssjqField;
        
        private string jksssjzField;
        
        private double hzjmseField;
        
        private string jmpzwshField;
        
        private string pzwsqsyField;
        
        private string pzwszzyField;
        
        /// <remarks/>
        public long lc {
            get {
                return this.lcField;
            }
            set {
                this.lcField = value;
            }
        }
        
        /// <remarks/>
        public double ynse {
            get {
                return this.ynseField;
            }
            set {
                this.ynseField = value;
            }
        }
        
        /// <remarks/>
        public string ynjkpzh {
            get {
                return this.ynjkpzhField;
            }
            set {
                this.ynjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public double yjse {
            get {
                return this.yjseField;
            }
            set {
                this.yjseField = value;
            }
        }
        
        /// <remarks/>
        public string yjjkpzh {
            get {
                return this.yjjkpzhField;
            }
            set {
                this.yjjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjq {
            get {
                return this.kjsssjqField;
            }
            set {
                this.kjsssjqField = value;
            }
        }
        
        /// <remarks/>
        public string kjsssjz {
            get {
                return this.kjsssjzField;
            }
            set {
                this.kjsssjzField = value;
            }
        }
        
        /// <remarks/>
        public string kjnsrsbh {
            get {
                return this.kjnsrsbhField;
            }
            set {
                this.kjnsrsbhField = value;
            }
        }
        
        /// <remarks/>
        public double yrkyysse {
            get {
                return this.yrkyysseField;
            }
            set {
                this.yrkyysseField = value;
            }
        }
        
        /// <remarks/>
        public string yrkjkpzh {
            get {
                return this.yrkjkpzhField;
            }
            set {
                this.yrkjkpzhField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjq {
            get {
                return this.jksssjqField;
            }
            set {
                this.jksssjqField = value;
            }
        }
        
        /// <remarks/>
        public string jksssjz {
            get {
                return this.jksssjzField;
            }
            set {
                this.jksssjzField = value;
            }
        }
        
        /// <remarks/>
        public double hzjmse {
            get {
                return this.hzjmseField;
            }
            set {
                this.hzjmseField = value;
            }
        }
        
        /// <remarks/>
        public string jmpzwsh {
            get {
                return this.jmpzwshField;
            }
            set {
                this.jmpzwshField = value;
            }
        }
        
        /// <remarks/>
        public string pzwsqsy {
            get {
                return this.pzwsqsyField;
            }
            set {
                this.pzwsqsyField = value;
            }
        }
        
        /// <remarks/>
        public string pzwszzy {
            get {
                return this.pzwszzyField;
            }
            set {
                this.pzwszzyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("V1.0")]
        V10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLName {
        
        /// <remarks/>
        sbbYdtgjzylwskjnqksbb,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public enum T_taxMLCnName {
        
        /// <remarks/>
        异地提供建筑业劳务税款缴纳情况申报表,
    }
}
